language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
matrix:
  include:
    - node_js: '0.12'
    - node_js: iojs
    - node_js: 4
    - node_js: 6
    - node_js: node
      env: COVERALLS=1
before_install:
  - export CXX=g++-4.8
